"""Subcommand dispatch for ``lamc migrate``.

Exposes three high-level operations that mirror knex.js:

    lamc migrate make   <name>    [--dir migrations]
    lamc migrate up     [--dir migrations] [--steps N] --driver X --dsn Y
    lamc migrate down   [--dir migrations] [--steps N] --driver X --dsn Y
    lamc migrate status            [--dir migrations] --driver X --dsn Y

``make`` is pure Python — it just scaffolds a timestamped ``.sql``
file with the conventional ``-- +lam up`` / ``-- +lam down`` markers.

``up`` / ``down`` / ``status`` need a live database connection. Rather
than pulling Python DB drivers (which would duplicate what
``lamdb`` already wraps for Go), we generate a tiny Lam program on the
fly, compile it through the existing pipeline, and run it. The runner
is ephemeral so no state leaks between invocations.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys
import tempfile
from pathlib import Path


_MIGRATION_SCAFFOLD = """\
-- Migration generated by `lamc migrate make {name}` at {iso}.
--
-- Edit the two sections below — the runner splits on the
-- ``-- +lam up`` / ``-- +lam down`` markers, so keep them on
-- their own lines and spell them exactly as shown. Everything
-- between ``-- +lam up`` and ``-- +lam down`` is applied when you
-- run ``lamc migrate up``; everything after ``-- +lam down``
-- is applied when you run ``lamc migrate down``.

-- +lam up
-- CREATE TABLE IF NOT EXISTS {slug} (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- +lam down
-- DROP TABLE IF EXISTS {slug};
"""


def _slugify(name: str) -> str:
    """Turn a free-form migration name into a safe filename fragment.

    Preserves alphanumerics and underscores, collapses everything
    else to ``_``. Prevents accidentally generating filenames with
    shell-sensitive characters.
    """
    cleaned = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip()).strip("_")
    return cleaned.lower() or "migration"


def _timestamp() -> str:
    """UTC ``YYYYMMDDHHMMSS`` — mirrors knex's ``migrations.make`` output."""
    return _dt.datetime.utcnow().strftime("%Y%m%d%H%M%S")


def _cmd_make(args: argparse.Namespace) -> int:
    mig_dir = Path(args.dir).resolve()
    mig_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(args.name)
    filename = f"{_timestamp()}_{slug}.sql"
    path = mig_dir / filename
    if path.exists():
        print(f"error: {path} already exists", file=sys.stderr)
        return 1
    path.write_text(
        _MIGRATION_SCAFFOLD.format(
            name=args.name,
            slug=slug,
            iso=_dt.datetime.utcnow().isoformat() + "Z",
        ),
        encoding="utf-8",
    )
    print(f"[lamc migrate] created {path}")
    return 0


def _escape(value: str) -> str:
    """Escape a string for embedding inside a double-quoted Lam literal.

    Only needs to handle ``\\`` and ``"`` — Lam string literals don't
    interpret any other backslash escapes when the runner generates
    them in ``_build_runner_program``.
    """
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _build_runner_program(
    driver: str, dsn: str, mig_dir: str, verb: str, steps: int
) -> str:
    """Return a self-contained Lam program that performs ``verb`` and
    prints the result as JSON-ish key/value lines the CLI can echo.

    The shape is intentionally minimal — no YAML, JSON, or multiline
    formatting — because the CLI just passes stdout through. Anything
    more structured would need a shared serialiser, which isn't worth
    the coupling for a CLI helper.
    """
    driver_e = _escape(driver)
    dsn_e = _escape(dsn)
    dir_e = _escape(mig_dir)
    body = [
        'from lamdb import Db',
        'from lammigrate import Migrator',
        '',
        'func main() {',
        f'    db: Db = Db.connect("{driver_e}", "{dsn_e}")',
        f'    mig: Migrator = Migrator(db, "{dir_e}")',
        '    mig.ensureSchema()',
    ]
    if verb == "status":
        body += [
            '    info: dict[str, any] = mig.status()',
            '    print("total: " + str(info["total"]))',
            '    print("ran: " + str(info["ran"]))',
            '    print("pending: " + str(info["pending"]))',
            '    print("lastBatch: " + str(info["lastBatch"]))',
            '    ranList: list[str] = []',
            '    pendingList: list[str] = []',
            '    go! {',
            '        if v, ok := info["ranNames"].([]string); ok { ranList = v }',
            '        if v, ok := info["pendingNames"].([]string); ok { pendingList = v }',
            '    }',
            '    for n in ranList { print("ran-file: " + n) }',
            '    for n in pendingList { print("pending-file: " + n) }',
        ]
    elif verb == "up":
        body += [
            f'    applied: list[str] = mig.up({int(steps)})',
            '    print("applied-count: " + str(len(applied)))',
            '    for n in applied { print("applied: " + n) }',
        ]
    elif verb == "down":
        body += [
            f'    undone: list[str] = mig.down({int(steps)})',
            '    print("rolled-back-count: " + str(len(undone)))',
            '    for n in undone { print("rolled-back: " + n) }',
        ]
    else:
        raise ValueError(f"unknown verb: {verb}")
    body += [
        '    db.close()',
        '}',
        '',
    ]
    return "\n".join(body)


def _run_generated(
    program: str, *, stdlib_path: str | None, verbose: bool = False
) -> int:
    """Write the generated program to a tempfile, compile it with
    the existing ``compile_lam`` pipeline, and run it.

    We reuse the compiler's own ``run`` flag so the standard error
    formatting / Go-source display for failures is consistent with
    the rest of the toolchain.
    """
    # Import lazily so ``lamc --help`` doesn't pay the Lark import cost.
    from compiler.lammergeier import compile_lam, PROJECT_ROOT

    with tempfile.NamedTemporaryFile(
        suffix=".lam", delete=False, prefix="lam_migrate_", mode="w"
    ) as f:
        f.write(program)
        src_path = f.name

    try:
        if stdlib_path is None:
            default_stdlib = PROJECT_ROOT / "stdlib"
            if default_stdlib.is_dir() and any(default_stdlib.glob("*.go")):
                stdlib_path = str(default_stdlib)
        try:
            compile_lam(
                source_path=src_path,
                run=True,
                stdlib_path=stdlib_path,
                verbose=verbose,
            )
        except SystemExit as exc:
            return int(exc.code or 0)
        return 0
    finally:
        try:
            os.unlink(src_path)
        except OSError:
            pass


def _cmd_db(args: argparse.Namespace, verb: str) -> int:
    if not args.driver or not args.dsn:
        print(
            f"error: lamc migrate {verb} requires --driver and --dsn",
            file=sys.stderr,
        )
        return 2
    mig_dir = str(Path(args.dir).resolve())
    if not Path(mig_dir).is_dir():
        print(f"error: migration directory not found: {mig_dir}", file=sys.stderr)
        return 1
    steps = getattr(args, "steps", 0) or 0
    program = _build_runner_program(args.driver, args.dsn, mig_dir, verb, steps)
    return _run_generated(program, stdlib_path=args.stdlib, verbose=args.verbose)


def main(argv: list[str]) -> int:
    """Entry point for ``lamc migrate``.

    Returns the intended process exit code — the outer ``lamc`` CLI
    is responsible for calling ``sys.exit`` with the value returned
    here.
    """
    ap = argparse.ArgumentParser(
        prog="lamc migrate",
        description=(
            "Knex-style SQL migration runner. Each migration is a "
            "`.sql` file with `-- +lam up` / `-- +lam down` sections; "
            "the runner records applied files in a `lam_migrations` "
            "table for idempotency."
        ),
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    # ``--dir``, ``--stdlib`` and ``-v`` accepted on every
    # subcommand so ``lamc migrate make foo --dir bar`` reads the
    # same as ``lamc migrate --dir bar make foo`` — argparse
    # subparsers don't inherit from the outer parser by default,
    # so attach them via a shared parent.
    shared = argparse.ArgumentParser(add_help=False)
    shared.add_argument(
        "--dir",
        default="migrations",
        help="Directory holding migration .sql files (default: ./migrations).",
    )
    shared.add_argument(
        "--stdlib",
        default=None,
        help="Override the path to the lamc Go stdlib directory.",
    )
    shared.add_argument(
        "-v", "--verbose", action="store_true",
        help="Pass verbose flag through to the embedded compile step.",
    )

    make_p = sub.add_parser(
        "make",
        parents=[shared],
        help="Scaffold a new timestamped migration file.",
    )
    make_p.add_argument("name", help="Human-readable migration name.")

    up_p = sub.add_parser(
        "up",
        parents=[shared],
        help="Apply pending migrations (all, or --steps N).",
    )
    up_p.add_argument("--driver", required=True,
                      help="Database driver: sqlite, mysql, or postgres.")
    up_p.add_argument("--dsn", required=True,
                      help="Driver-specific connection string / path.")
    up_p.add_argument("--steps", type=int, default=0,
                      help="How many migrations to apply; 0 means all pending.")

    down_p = sub.add_parser(
        "down",
        parents=[shared],
        help="Roll back migrations. Default rewinds the last batch.",
    )
    down_p.add_argument("--driver", required=True)
    down_p.add_argument("--dsn", required=True)
    down_p.add_argument("--steps", type=int, default=1,
                        help="Number of steps. 1 == last batch.")

    status_p = sub.add_parser(
        "status",
        parents=[shared],
        help="Print how many migrations have run and which are pending.",
    )
    status_p.add_argument("--driver", required=True)
    status_p.add_argument("--dsn", required=True)

    args = ap.parse_args(argv)

    if args.cmd == "make":
        return _cmd_make(args)
    if args.cmd == "up":
        return _cmd_db(args, "up")
    if args.cmd == "down":
        return _cmd_db(args, "down")
    if args.cmd == "status":
        return _cmd_db(args, "status")

    ap.print_help()
    return 2
